apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-webserver
  template:
    metadata:
      labels:
        app: go-webserver
    spec:
      containers:
      - name: go-webserver
        image: image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8090
