apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: go-webserver
images:
- name: image
  newName: luizfernadomarques/go-webserver
  newTag: e635448d914f6e534617857a998e3c57629d0efe
