---
name: "Deploy K8S PROD General"

on:
  workflow_dispatch:
# on:
#     push:
#         branches:
#             - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # - name: Build docker image
    #   run: docker build --file docker/Dockerfile --tag go-webserver:latest .
    - name: build image and push to docker hub
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/go-webserver
        tags: ${{ github.sha }}

    - name: Checkout GitHub Action Repo
      uses: actions/checkout@v2
      with:
        repository: nandoin/argocd
        ref: main
        #token: ${{ secrets.GIT_HUB_TOKEN }}
        path: .github/argocd

        
    - name: Deploy yy-gympass
      uses: ./.github/argocd/actions/deploy_kubernetes
      with:         
        environment: production
        name: yy-gympass
        namespace: yy-gympass
        image: go-webserver:${{ github.sha }}
        github_token: ${{ secrets.SSH_KEY }}
        version: ${{ github.sha }}

    - name: Deploy yy-samsung
      uses: ./.github/argocd/actions/deploy_kubernetes
      with:         
        environment: production
        name: yy-samsung
        namespace: go-samsung
        image: go-webserver:${{ github.sha }}
        github_token: ${{ secrets.SSH_KEY }}
        version: ${{ github.sha }}
